# Generated by Django 5.0.3 on 2024-03-27 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='current_location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='delivery_app.location'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='unique_number',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
